Adds airbrake for error reporting.
imgproxy/imgproxy pull request #603
Opened 2021-03-29 16:20 UTC by bantonj

Not sure how popular airbrake is, but it's something we use, so thought I'd open this PR in case others might find it useful.

2021-04-26 12:39 UTC, DarthSim requested changes
Hi Joshua!

Please fix the things I mentioned and I'll merge this.

2021-04-26 12:39 UTC, DarthSim commented on config.go
> +
No need for a custom parser for `int64`. You can parse the ID to int and cast it to `int64` here: https://github.com/imgproxy/imgproxy/pull/603/files#diff-695e64e5ace3a24d0e73f02a3555553fa8df9d9045bf759fb729ef870eb62c61R54

2021-04-26 12:39 UTC, DarthSim commented on main.go
> +
Please move this to `run` after `shutdownVips`

2021-05-13 16:42 UTC, bantonj commented
> Hi Joshua!
> 
> Please fix the things I mentioned and I'll merge this.

Thanks for taking a look. I think I resolved the items you mentioned.

2021-05-17 10:05 UTC, merged

2021-05-17 10:05 UTC, DarthSim commented
Thanks for your contribution!